httpserver:
  image: nginx
  links: 
    - php
  ports:
    - "80:80"
  volumes:
    - ./log/nginx:/var/log/nginx
    - ./var/www:/var/www
    - ./var/xoops_data:/var/xoops_data
    - ./var/xoops_lib:/var/xoops_lib
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./conf.d/:/etc/nginx/conf.d/

php:
  build: ./docker-php
  links:
    - db
  expose:
    - "9000"
  volumes:
    - ./var/www:/var/www
    - ./var/xoops_data:/var/xoops_data
    - ./var/xoops_lib:/var/xoops_lib

db:
  image: mysql:5.5
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

